apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-ui
    kubernetes.io/name: KubeUI
  name: kube-ui
  namespace: kube-system
subsets:
- addresses:
  - ip: {{ pillar['kube_ui_public'] }}
  ports:
  - port: 8080
    protocol: TCP
